--- #YAML:1.0
name:                DBD-Unify
version:             0.61
abstract:            DBI driver for Unify database systems
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    DBI:                           1.42
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - H.Merijn Brand <h.m.brand@xs4all.nl>
